language: node_js

node_js:
  - "node"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      node_js:
        - "node"

    - language: rust
      install:
        - npm install neon-cli
      script:
        - "neon build"
