language: node_js

node_js:
  - "node"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_script:
        - "cd lib/"

    - language: rust
      install: skip
      before_script:
        - "cd native/"
      script:
        - cargo test --verbose --all
