notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  allow_failures:
    - rust: nightly
    
  include:
    - language: node_js
      node_js:
        - "node"

    - language: rust
      rust:
        - nightly
      install:
        - npm install --global neon-cli
      script:
        - "neon build"
