notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      install:
        - npm install --global neon-cli
      node_js:
        - "neon build"
        - "node"

    - language: rust
      install:
        - npm install --global neon-cli
      script:
        - "neon build"
