notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      node_js:
        - "node"

    - language: rust
      install:
        - npm install --global neon-cli
        - rustup install nightly
        - cargo +nightly install clippy
      script:
        - "neon build"
