notifications:
  email: false

matrix:
  include:
    - language: node_js
      node_js:
        "8.11.2"
      install:
        - curl https://sh.rustup.rs -sSf | sh -s -- -y
        - npm install --global neon-cli
        - npm install -f
      script:
        - "neon build"
        - "npm test"

    - language: rust
      install:
        - npm install --global neon-cli
      script:
        - "neon build"
