notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      install:
        - echo 1 | curl https://sh.rustup.rs -sSf | sh
        - npm install --global neon-cli
      script:
        - "neon build"
        - "npm test"

    - language: rust
      install:
        - npm install --global neon-cli
      script:
        - "neon build"
