notifications:
  email: false

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      node_js:
        - "node"

    - language: rust
      rust:
        - 1.28.0
      install:
        - npm install --global neon-cli
      script:
        - "neon build"
