[package]
name = "sw-ki"
version = "0.1.0"
authors = ["reinkepatrick <patrick.reinke@fh-bielefeld.de>", "martistuwe"]
license = "MIT"
build = "build.rs"

[lib]
name = "sw_ki"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
chess-move-gen = "0.5.0"
